### ISSUE TITLE
Copy an email template to active theme's UM folder and "PHP Fatal error"

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1082]
**Expected behavior**
Failing to copy an email template to active theme's UM folder should not result in the error "There has been a critical error on this website."

**Describe the bug**
`function copy_email_template` is returning a failure which is not tested by the caller `function save_email_templates`

**Expected behavior**
When `function copy_email_template` is returning `false`  don't attempt to file open and write to the template file.
Make current error exit also based on the `function copy_email_template` return value.

**New Feature**
Introduce an UM error log file for tracing of existing file failures.

**Debug.log**
```
[12-Oct-2022 15:29:45 UTC] PHP Warning: copy(/wordpress/themes/pub/radcliffe-2/ultimate-member/email/notification_review.php): Failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/ultimate-member/includes/core/class-mail.php on line 579
[12-Oct-2022 15:29:45 UTC] PHP Warning: fopen(/wordpress/themes/pub/radcliffe-2/ultimate-member/email/notification_review.php): Failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php on line 3466
[12-Oct-2022 15:29:45 UTC] PHP Fatal error: Uncaught TypeError: fputs(): Argument #1 ($stream) must be of type resource, bool given in /srv/htdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php:3467
Stack trace:
#0 /srv/htdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php(3467): fputs(false, \'<div style=\”max…\’)
#1 /wordpress/core/6.0.2/wp-includes/class-wp-hook.php(307): um\\admin\\core\\Admin_Settings->save_email_templates(Array)
#2 /wordpress/core/6.0.2/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#3 /srv/htdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php(2214): apply_filters(\’um_change_setti…\’, Array)
#4 /wordpress/core/6.0.2/wp-includes/class-wp-hook.php(307): um\\admin\\core\\Admin_Settings->save_settings_handler(\’\’)
#5 /wordpress/core/6.0.2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/core/6.0.2/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7 /wordpress/core/6.0.2/wp-admin/admin.php(175): do_action(\’admin_init\’)
#8 {main}
thrown in /srv/htdocs/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php on line 3467
```

**UM Support Forum issue**
https://wordpress.org/support/topic/enable-email-notifications/

**Comment by MissVeronica** [comment]
Support Forum issue: https://wordpress.org/support/topic/email-notification-settings-adjustments-causes-crash/

In this case WP returned an empty theme folder by the UM call to the WP `function get_stylesheet_directory()` 
with the result that UM tried to create the UM templates folder in the root folder. 

This was detected by the UM permissions code snippet  when the expected theme folder was empty.
