### ISSUE TITLE
UM 2.5.2 and Fatal Error when updating from very old versions of UM

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1110]
**Describe the bug**
UM is calling `current_user_can('manage_options') `and WP function pluggable is not loaded yet when `wp_get_current_user` is called. This happens when upgrading from UM 2.3.1 with the DB update job starting.
```
Stack trace:
#0 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-upgrade.php(70): current_user_can('manage_options')
#1 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-upgrade.php(53): um\admin\core\Admin_Upgrade->__construct()
#2 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/class-init.php(810): um\admin\core\Admin_Upgrade::instance()
#3 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/class-init.php(551): UM->admin_upgrade()
#4 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/class-init.php(204): UM->includes()
#5 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/class-init.php(88): UM->_um_construct()
#6 /nas/content/live/sibcr1/wp-content/plugins/ultimate-member/includes/class-init.php(1526): UM::instance()
#7 /nas/ in /nas/content/live/sibcr1/wp-includes/capabilities.php on line 873
[15-Dec-2022 22:12:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_get_current_user() in /nas/content/live/sibcr1/wp-includes/capabilities.php:873
```

**UM Support Forum**
https://wordpress.org/support/topic/latest-update-2-5-2-fatal-error/

**Comment by MissVeronica** [comment]
New UM Support Forum issue https://wordpress.org/support/topic/ultimate-member-version-2-5-2-needs-to-be-update-to-work-correctly/

**Comment by MissVeronica** [comment]
Quick fix for this issue if you are updating from a very old UM version like 2.3 or 2.4 or older.
1. Download and update to UM 2.5.1 https://github.com/ultimatemember/ultimatemember/releases/tag/2.5.1
2. Update from UM 2.5.1 to UM 2.5.2
