### ISSUE TITLE
Crash after editing UM 2.6.8 security settings

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1261]
**Describe the bug**
```
[22-Jul-2023 22:05:00 UTC] PHP Warning:  Attempt to read property "capabilities" on null in /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php on line 888
[22-Jul-2023 22:05:00 UTC] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php:889
Stack trace:
#0 /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php(889): array_keys(NULL)
#1 /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php(877): um\admin\core\Admin_Notices->check_new_user_role()
#2 /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php(64): um\admin\core\Admin_Notices->common_secure()
#3 /docroot/wp-includes/class-wp-hook.php(308): um\admin\core\Admin_Notices->create_list('')
#4 /docroot/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /docroot/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /docroot/wp-admin/admin.php(175): do_action('admin_init')
#7 /docroot/wp-admin/plugins.php(10): require_once('/home/grys/memb...')
#8 {main}
  thrown in /docroot/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-notices.php on line 889
```

**Support Forum issue**
https://wordpress.org/support/topic/crash-after-editing-um-security-settings/

**Comment by justdave** [comment]
Root cause: WP_Role->capabilities returns NULL rather than an empty list if the role has no capabilities, so the return value needs to be checked for NULL before trying to iterate it.
