### ISSUE TITLE
PHP Warning when WPML is enabled and language switcher is added to menu

### ISSUE THREAD

**Issue by joostdekeijzer** [ultimatemember/ultimatemember#894]
**Expected behavior**
No PHP Warnings in error.log

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
With UM and WPML plugin enabled *and* when you add a language switcher to a menu, eg. the theme's main menu, you get a PHP Waring on every page load:

```
PHP Warning:  Attempt to read property "ID" on string in /wp-content/plugins/ultimate-member/includes/core/class-access.php on line 704
```

I've added a temp. `error_log()` above line 704 and the value of `$post` can be something like 'wpml-ls-9-nl'.

**To Reproduce**
1. Enable UM and WPML
2. Configure WPML with languages and add a language switcher to a menu on page /wp-admin/admin.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php
3. Save save save
4. Enable error logging in WP
5. Go to homepage of test site (or any page containing the menu you configured the language switcher in)
6. See php error.log

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
```
### Begin Install Info ###

## Please include this information when posting support requests ##


--- Site Info ---

Site URL:					http://<sorry, private> (local development machine)
Home URL:					http://<sorry, private>/nl/
Multisite:					No

--- Hosting Provider ---

Host:						DBH: localhost, SRV: <sorry, private>

--- User Browser ---

Platform:                 Apple 
Browser Name:             Safari  
Browser Version:          14.1.2 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_15_7) AppleWebKit/605.
                          1.15 (KHTML, like Gecko) Version
                          /14.1.2 Safari/605.1.15
                          
---- Current User Details --

Role: administrator


--- WordPress Configurations ---

Version:						5.8
Language:					nl_NL
Permalink Structure:			/%year%/%monthnum%/%postname%/
Active Theme:				<sorry, private> 0.11
Page On Front:				<sorry, private> (#2)
Page For Posts:				 (#0)
ABSPATH:					<sorry, private>/public_html/
All Posts/Pages:				8
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Enabled
WP Table Prefix:          			Length: 3, Status: Acceptable
Memory Limit:   				40MB


--- UM Configurations ---

Version:						2.2.2
Upgraded From:            		2.1.21
Current URL Method:			
Cache User Profile:			Yes
Generate Slugs on Directories:	Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			Yes
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						http://<sorry, private>/nl/dashboard/
Account:						http://<sorry, private>/nl/account/
Members:					http://<sorry, private>/nl/members/
Register:						http://<sorry, private>/nl/register/
Login:						http://<sorry, private>/nl/login/
Logout:						http://<sorry, private>/nl/logout/
Password Reset:				http://<sorry, private>/nl/password-reset/


--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		user_id
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		No
Enable Members Directory:	No
Use Gravatars: 				No
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Everyone
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			Yes
Reset Password Limit: 3Disable Reset Password Limit for Admins: No
Blacklist Words: 							5


--- UM Email Configurations ---

Mail appears from:  			<sorry, private>
Mail appears from address:  	<sorry, private>
Use HTML for E-mails:   		Yes
Account Welcome Email:  		Yes
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	Yes
Account Deleted Email:  		Yes
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

				All Users(2)
administrator(1)
subscriber(1)
none(0)


--- UM Roles ---

				Administrator (administrator)
Editor (editor)
Author (author)
Contributor (contributor)
Subscriber (subscriber)


--- UM Custom Templates ---

				N/A


--- UM Email HTML Templates ---

				N/A


--- Web Server Configurations ---

PHP Version:              			8.0.8
MySQL Version:            			5.5.5
Web Server Info:          			Apache/2.4.48 (Unix) PHP/7.4.21


--- PHP Configurations ---

PHP Memory Limit:         			256M
PHP Upload Max Size:      			32M
PHP Post Max Size:        			32M
PHP Upload Max Filesize:  			32M
PHP Time Limit:           			30
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

				Contact Form 7 Multilingual: 1.1.0
Export media with selected content: 2.1.3
Login Logo: 0.10.0
Regenerate Thumbnails: 3.1.5
Ultimate Member: 2.2.2
User Switching: 1.5.7
WPML Media: 2.6.4
WPML Multilingual CMS: 4.4.10
WPML String Translation: 3.1.8
WPML Translation Management: 2.10.6
Yoast Duplicate Post: 4.1.2

### End Install Info ###

```
</details>

**Comment by nikitasinelnikov** [comment]
Hi @joostdekeijzer 

Thanks for your feedback, please check this branch with the latest hotfixes
https://github.com/ultimatemember/ultimatemember/tree/development/2.2.3

Let me know if you still have the PHP warnings,
Best Regards!

**Comment by joostdekeijzer** [comment]
Just downloaded (10:30 CET) and can't test since I get a PHP Fatal Error (default WP theme, all plugins disabled)

```
[19-Aug-2021 08:35:24 UTC] PHP Fatal error:  Uncaught TypeError: array_intersect(): Argument #2 must be of type array, string given in /wp-content/plugins/ultimate-member/includes/core/class-access.php:332
Stack trace:
#0 /wp-content/plugins/ultimate-member/includes/core/class-access.php(332): array_intersect(Array, '')
#1 /wp-content/plugins/ultimate-member/includes/core/class-access.php(384): um\core\Access->exclude_terms_array(Object(WP_Term_Query))
#2 /wp-includes/class-wp-hook.php(303): um\core\Access->exclude_hidden_terms_query(Object(WP_Term_Query))
#3 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#5 /wp-includes/class-wp-term-query.php(358): do_action_ref_array('pre_get_terms', Array)
#6 /wp-includes/class-wp-term-query.php(301): WP_Term_Query->get_terms()
#7 /wp-includes/taxonomy.php(1275): WP_Term_Query->query(Array)
#8 /wp-includes/taxonomy.php(2186): get_terms(Array)
#9 /wp-includes/taxonomy.php(3668): wp_get_object_terms(Array, Array, Array)
#10 /wp-includes/post.php(7245): update_object_term_cache(Array, Array)
#11 /wp-includes/class-wp-query.php(3212): update_post_caches(Array, 'any', true, true)
#12 /wp-includes/class-wp-query.php(3465): WP_Query->get_posts()
#13 /wp-includes/class-wp.php(629): WP_Query->query(Array)
#14 /wp-includes/class-wp.php(752): WP->query_posts()
#15 /wp-includes/functions.php(1291): WP->main('')
#16 /wp-blog-header.php(16): wp()
#17 /index.php(17): require('/...')
#18 {main}
  thrown in /wp-content/plugins/ultimate-member/includes/core/class-access.php on line 332
```

**Comment by nikitasinelnikov** [comment]
Hi @joostdekeijzer 

Sorry, please try again. There was an error when restricted taxonomies are disabled.

Best Regards!

**Comment by joostdekeijzer** [comment]
> Hi @joostdekeijzer
> 
> Sorry, please try again. There was an error when restricted taxonomies are disabled.
> 
> Best Regards!

The PHP Warnings are gone, but so is my menu!!!

So I'm afraid this beta version is worse 😞 

Please test thoroughly with WPML!!!

**Comment by nikitasinelnikov** [comment]
Hi @joostdekeijzer 

Thanks for letting me know!
Please check that your menu items are not restricted (have restriction settings as a menu item or as menu object: individual post/term).

Could you share the menu items settings here?

Let me know,
Best Regards!

**Comment by joostdekeijzer** [comment]
Hi @nikitasinelnikov,

There are 'restricted items' in my menu, but removing those restrictions does not help. v2.2.2 generates PHP Warnings and v2.2.3-beta removes language switcher.

I did notice that issues in both versions only occur for not-logged-in visitors, when logged-in (as an admin in my case) I don't see warning (v2.2.2) and do see the language switcher (v2.2.3).

WMPL language switcher settings:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/216672/130418918-91c23266-9356-401b-bce2-df7b270e97da.png">

**Comment by nikitasinelnikov** [comment]
Hi @joostdekeijzer 

Please check how the latest commit to development/2.2.3 branch works. We have added the fix.

Let me know,
Best Regards!

**Comment by joostdekeijzer** [comment]
@nikitasinelnikov I see the dev branch is gone and we have a new release! 🙌 

I can confirm the issue is resolved: no more warnings and no crashes on the menu.
